In [2]:
import numpy as np
arr=np.arange(10,dtype=np.uint16)
np.save('demo.npy',arr)

back=np.load('demo.npy')
print(type(back))
print(back, back.dtype, back.shape)


<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9] uint16 (10,)


In [2]:
import os
print(os.getcwd())
print(os.listdir())
print(os.listdir('..'))

c:\Users\lenovo\Desktop\deep-learning\karpathy\reproduce_gpt2
['build-nanogpt', 'demo.npy', 'hellaswag', 'hellaswag.py', 'input.txt', 'test.py', 'try.ipynb', '__pycache__', '读代码方法论.md']
['.claude', 'Andrej Karpathy《Neural Networks_ Zero to Hero》逐集完整大纲.pdf', 'build-gpt', 'code_lines.sqlite', 'day1', 'day2', 'day3', 'day4', 'day5', 'day6', 'nn_zero_to_hero_textbook.agent.final.md', 'reproduce_gpt2', 'scripts', 'songci-nanogpt']


{"ind": 4, 
"activity_label": "Removing ice from car", 
"ctx_a": "Then, the man writes over the snow covering the window of a car, and a woman wearing winter clothes smiles.",
"ctx_b": "then", 
"ctx": "Then, the man writes over the snow covering the window of a car, and a woman wearing winter clothes smiles. then", 
"split": "train", 
"split_type": "indomain",
"label": 3,
"endings": [
    ", the man adds wax to the windshield and cuts it.", ", a person board a ski lift, while two men supporting the head of the person wearing winter clothes snow as the we girls sled.",
     ", the man puts on a christmas coat, knitted with netting.",
      ", the man continues removing the snow on his car."], 
"source_id": "activitynet~v_-1IBHYS3L-Y"}

In [3]:
from hellaswag import iterate_examples,render_example
iterate_examples('val')

c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.4.3)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(


<generator object iterate_examples at 0x0000022A85BB0AE0>

In [4]:
ex=next(iterate_examples('val'))
ex

{'ind': 24,
 'activity_label': 'Roof shingle removal',
 'ctx_a': 'A man is sitting on a roof.',
 'ctx_b': 'he',
 'ctx': 'A man is sitting on a roof. he',
 'split': 'val',
 'split_type': 'indomain',
 'label': 3,
 'endings': ['is using wrap to wrap a pair of skis.',
  'is ripping level tiles off.',
  "is holding a rubik's cube.",
  'starts pulling up roofing on a roof.'],
 'source_id': 'activitynet~v_-JhWjGDPHMY'}

In [5]:
data, tokens, mask, label=render_example(ex)
type(tokens)
# 源文件有 # TO DEL
#  print(type(ctx_tokens))
# 但是没打印，原因是：
# Jupyter 的 kernel 一旦 from hellaswag import render_example,这个函数对象就钉死在内存里。你后面改源文件,kernel 不知道——除非你主动 reload 或重启。
# 你那次 from hellaswag import iterate_examples, render_example cell 之后,render_example 这个名字就指向旧版的函数对象。
# 重新跑那个 import cell 也没用,因为 sys.modules['hellaswag'] 已经缓存,import 直接返回缓存,不重读文件。



torch.Tensor

In [6]:
data

{'label': 3,
 'ctx_tokens': [32, 582, 318, 5586, 319, 257, 9753, 13, 339],
 'ending_tokens': [[318,
   1262,
   14441,
   284,
   14441,
   257,
   5166,
   286,
   1341,
   271,
   13],
  [318, 34759, 1241, 19867, 572, 13],
  [318, 4769, 257, 6437, 1134, 338, 23441, 13],
  [4940, 10427, 510, 9753, 278, 319, 257, 9753, 13]]}

In [7]:
tokens[0]==data['ctx_tokens']+data['ending_tokens'][0]
# why??

False

In [8]:
tokens

tensor([[   32,   582,   318,  5586,   319,   257,  9753,    13,   339,   318,
          1262, 14441,   284, 14441,   257,  5166,   286,  1341,   271,    13],
        [   32,   582,   318,  5586,   319,   257,  9753,    13,   339,   318,
         34759,  1241, 19867,   572,    13,     0,     0,     0,     0,     0],
        [   32,   582,   318,  5586,   319,   257,  9753,    13,   339,   318,
          4769,   257,  6437,  1134,   338, 23441,    13,     0,     0,     0],
        [   32,   582,   318,  5586,   319,   257,  9753,    13,   339,  4940,
         10427,   510,  9753,   278,   319,   257,  9753,    13,     0,     0]])

In [9]:
tokens[0].shape


torch.Size([20])

In [10]:
(data['ctx_tokens']+data['ending_tokens'][0])

[32,
 582,
 318,
 5586,
 319,
 257,
 9753,
 13,
 339,
 318,
 1262,
 14441,
 284,
 14441,
 257,
 5166,
 286,
 1341,
 271,
 13]

In [11]:
# 没事了 类型不一样 草
import torch
tokens[0]==torch.tensor(data['ctx_tokens']+data['ending_tokens'][0])

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True])

In [12]:
# or from tensor to list
tokens[0].tolist()==data['ctx_tokens']+data['ending_tokens'][0]

True

In [13]:
# data, tokens, mask, label=render_example(ex)
type(mask[0].size().numel())
#int
mask[0].numel()

20

gooood

In [14]:
type(ex)

dict

In [15]:
ex.keys()

dict_keys(['ind', 'activity_label', 'ctx_a', 'ctx_b', 'ctx', 'split', 'split_type', 'label', 'endings', 'source_id'])

In [16]:
eval('3*3')

9

In [17]:
global_namespace={
    'x':2,
    'f':lambda x:x**2
}
local_namespace={
    'x':3,
    'f':lambda x:x**3
}
eval('x',global_namespace)

2

In [18]:
# eval(expression[, globals[, locals]])
eval('x',local_namespace)
# 按照签名不是不能只传局部不传全局吗 这没报错啊
# 确实，实际上把local_namespace当成全局传进去了，看的是位置不是名字

3

In [19]:
eval('x',global_namespace,local_namespace)
# 局部优先

3

In [20]:
eval('x',local_namespace,global_namespace)
#global_namespace 生效，说明默认就是后面的是局部，前面的是全局
# 只传一个默认是全局

2

In [21]:
eval('f(x)',global_namespace,local_namespace)
#local_namespace生效 
# 函数也是可以的

27

In [22]:
#   pred_norm = avg_loss.argmin().item()
avg_loss=torch.tensor([2.3,1.4,5.0,7])
print(avg_loss.argmin())
print(avg_loss.argmin().item())

tensor(1)
1


In [23]:
os.environ

environ{'ALLUSERSPROFILE': 'C:\\ProgramData',
        'ANTHROPIC_AUTH_TOKEN': 'sk-cp-Q2F1jCEmuy1JY2RH9sGC_DboYvaPNQ2hKvrUvEfvSYWqTFoIgu33CC33CGGPZD7YE1V4cDa_o9Nme9KhJakrtWxnarfKhvV2NRn-8WvzJgVjHl-EeykjhAM',
        'ANTHROPIC_BASE_URL': 'https://cn.luckyapi.chat',
        'API_KEY': 'PPuLjw1oyTLGMXIz1VYUIuhqZT9axlhG7EPh5Sz5kIYb1XjZHgsf5QsWWeYfsQ0N',
        'APPDATA': 'C:\\Users\\lenovo\\AppData\\Roaming',
        'BASE_MODEL': 'step-3.5-flash',
        'BASE_URL': 'https://api.stepfun.com/v1/chat/completions',
        'CHROME_CRASHPAD_PIPE_NAME': '\\\\.\\pipe\\crashpad_34012_MLRBXOSQNWOEVIDK',
        'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
        'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
        'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
        'COMPUTERNAME': 'LAPTOP-80U2AB5J',
        'COMSPEC': 'C:\\windows\\system32\\cmd.exe',
        'CPLUS_INCLUDE_PATH': 'C:\\Users\\lenovo\\scoop\\apps\\gcc\\current\\include',
        '

In [24]:
os.environ.get('RANK', -1)

-1

In [25]:
torch.cuda.is_available()

True

In [26]:
torch.mps.is_available()

False

In [27]:
64*1024

65536

In [52]:
avg=0
for _ in  range(1000):
    x=torch.zeros(768)
    n=100
    for i in range(n):
        x+=torch.randn(768)

    x*=n**-0.5
    avg+=x.std()
avg/=1000
(avg-1).__abs__()

tensor(0.0012)