In [ ]:

words=open('names.txt','r').read().splitlines()
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [18]:
stoi={}
stoi['.']=0
# ord: char->int 
# chr: int->char
for i in range(26):
    stoi[chr(i+ord('a'))]=i+1
stoi.items()

dict_items([('.', 0), ('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5), ('f', 6), ('g', 7), ('h', 8), ('i', 9), ('j', 10), ('k', 11), ('l', 12), ('m', 13), ('n', 14), ('o', 15), ('p', 16), ('q', 17), ('r', 18), ('s', 19), ('t', 20), ('u', 21), ('v', 22), ('w', 23), ('x', 24), ('y', 25), ('z', 26)])

In [19]:
# 易错点: stoi.items() 不能是stoi,stoi就只遍历key了
itos={i:s for s,i in stoi.items()}
itos.items()

dict_items([(0, '.'), (1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e'), (6, 'f'), (7, 'g'), (8, 'h'), (9, 'i'), (10, 'j'), (11, 'k'), (12, 'l'), (13, 'm'), (14, 'n'), (15, 'o'), (16, 'p'), (17, 'q'), (18, 'r'), (19, 's'), (20, 't'), (21, 'u'), (22, 'v'), (23, 'w'), (24, 'x'), (25, 'y'), (26, 'z')])

In [24]:
import torch

# 构造训练集


xs,ys=[],[]
for word in words:
    chs=['.']+list(word)+['.']
    for ch1,ch2 in zip(chs,chs[1:]):
        ix1=stoi[ch1]
        ix2=stoi[ch2]
        xs.append(ix1)
        ys.append(ix2)

xs=torch.tensor(xs)
ys=torch.tensor(ys)


In [25]:
xs[:5]

tensor([ 0,  5, 13, 13,  1])

In [33]:
import torch.nn.functional as F 
xenc=F.one_hot(xs,num_classes=27).float()
yenc=F.one_hot(ys,num_classes=27).float()
xenc

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 1., 0., 0.]])

In [ ]:
W=torch.randn((27,27))
xenc.matmul(W)

tensor([[ 0.1702,  2.1313,  1.2310,  ..., -2.3219,  0.4762,  0.2945],
        [ 0.7863, -0.8090,  1.3925,  ...,  0.6951, -0.5733, -1.8027],
        [ 0.0955, -0.9595, -0.0267,  ..., -1.0055, -0.6355, -0.5105],
        ...,
        [-0.0218,  1.0586, -0.2113,  ...,  0.0686, -1.1837,  1.2724],
        [-0.3396, -0.5726, -0.8207,  ...,  1.8616,  0.5058, -0.6132],
        [-2.6559,  1.2084,  1.6722,  ...,  0.5567,  0.6455,  0.0402]])